# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BsyYpSvOJwl-swMc5S-l86U7d5Hyc1p_

###Установим библиотеку PySide6
"""

!pip install PySide6

import ipywidgets as widgets
from IPython.display import display, HTML
import base64
import io
from PIL import Image, ImageDraw

class ColabProfileApp:
    def __init__(self):
        self.profile_image = None
        self.setup_ui()

    def setup_ui(self):
        # Заголовок
        title = widgets.HTML("<h1 style='color: #2c3e50; text-align: center;'>Профиль студента МАИ</h1>")

        # Фото профиля
        self.photo_output = widgets.Output()
        self.draw_default_avatar()

        # Кнопка загрузки
        self.upload_btn = widgets.FileUpload(
            description='Загрузить фото',
            multiple=False
        )
        self.upload_btn.observe(self.on_upload, names='value')

        # Информация
        info_html = widgets.HTML("""
        <div style='background: #f8f9fa; padding: 20px; border-radius: 10px;'>
            <h3 style='color: #2c3e50;'>Янполь Софья</h3>

            <h4 style='color: #34495e;'>Биография</h4>
            <p style='color: #7f8c8d;'>Родилась во Владивостоке. С отличием закончила школу. Сейчас учусь в Московском Авиационном Институте на 2 курсе 3 факультета по специальности "Инноватика"</p>

            <h4 style='color: #34495e;'>Навыки</h4>
            <p style='color: #7f8c8d;'>Python | SQL </p>

            <h4 style='color: #34495e;'>Опыт работы</h4>
            <p style='color: #7f8c8d;'>
                <b>Продавец-консультант</b> (04.06.2024 - 01.09.2025)<br>
                <b>Репетитор</b> (01.09.2024 - настоящее время)
            </p>
        </div>
        """)

        # Собираем интерфейс
        display(widgets.VBox([
            title,
            self.photo_output,
            self.upload_btn,
            info_html
        ]))

    def draw_default_avatar(self):
        with self.photo_output:
            self.photo_output.clear_output()
            display(HTML("""
            <div style='
                width: 150px;
                height: 150px;
                background: #ecf0f1;
                border-radius: 50%;
                border: 3px solid #3498db;
                display: flex;
                align-items: center;
                justify-content: center;
                font-size: 16px;
                margin: 0 auto;
                text-align: center;
                line-height: 1.4;
            '>Фото<br>профиля</div>
            <p style='text-align: center; color: #95a5a6;'>Нажмите кнопку для загрузки фото</p>
            """))

    def on_upload(self, change):
        if not change['new']:
            return

        uploaded_file = list(change['new'].values())[0]
        image_data = uploaded_file['content']

        # Отображаем загруженное фото
        with self.photo_output:
            self.photo_output.clear_output()

            # Создаем круглое изображение
            image = Image.open(io.BytesIO(image_data))
            image = image.resize((150, 150))

            # Создаем круглую маску
            mask = Image.new('L', (150, 150), 0)
            draw = ImageDraw.Draw(mask)
            draw.ellipse((0, 0, 150, 150), fill=255)

            result = Image.new('RGBA', (150, 150))
            result.putalpha(mask)
            result.paste(image, (0, 0))

            # Конвертируем для отображения
            buffered = io.BytesIO()
            result.save(buffered, format="PNG")
            img_str = base64.b64encode(buffered.getvalue()).decode()

            display(HTML(f"""
            <div style='text-align: center;'>
                <img src='data:image/png;base64,{img_str}' style='
                    width: 150px;
                    height: 150px;
                    border-radius: 50%;
                    border: 3px solid #3498db;
                '>
                <p style='color: #27ae60;'>Фото успешно загружено!</p>
            </div>
            """))

# Запуск приложения
print("Приложение профиля студента МАИ запущено!")
app = ColabProfileApp()